name: Release - Build and Upload

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build Production Binary
        env:
          GOARCH: arm64
          GOOS: linux
          CGO_ENABLED: 0
        run: |
          go build -o bootstrap ./cmd/photo-lambda
          zip photo-lambda-${{ github.event.release.tag_name }}.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload ZIP to S3
        run: aws s3 cp photo-lambda-${{ github.event.release.tag_name }}.zip s3://${{ vars.BUCKET }}/photo-lambda/photo-lambda-${{ github.event.release.tag_name }}.zip